//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WestgateHomeVideoManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clip()
        {
            this.TagsCollections = new HashSet<TagsCollection>();
            this.TagsPeoples = new HashSet<TagsPeople>();
        }
    
        public int ClipID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> ClipNumber { get; set; }
        public Nullable<System.DateTime> ClipTimeStart { get; set; }
        public Nullable<System.DateTime> ClipTimeEnd { get; set; }
        public string ClipVidTimeStart { get; set; }
        public string ClipVidTimeEnd { get; set; }
        public string ClipVidTimeLength { get; set; }
        public string ClipReviewer { get; set; }
        public string CameraOperator { get; set; }
        public string Description { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsCollection> TagsCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsPeople> TagsPeoples { get; set; }
    }
}
