//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WestgateHomeVideoManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clip_Collections
    {
        public int SourceID { get; set; }
        public string SourceLabel { get; set; }
        public int ChapterID { get; set; }
        public Nullable<int> ChapterNumber { get; set; }
        public int ClipID { get; set; }
        public Nullable<int> ClipNumber { get; set; }
        public int CollectionsID { get; set; }
        public string CollectionsText { get; set; }
    }
}
