//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WestgateHomeVideoManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVD_Chapter_Clip
    {
        public int SourceID { get; set; }
        public string SourceLabel { get; set; }
        public Nullable<System.DateTime> SourceDateBurned { get; set; }
        public Nullable<System.DateTime> SourceDateRipped { get; set; }
        public int ChapterID { get; set; }
        public Nullable<int> ChapterNumber { get; set; }
        public string ChapterLength { get; set; }
        public int ClipID { get; set; }
        public Nullable<int> ClipNumber { get; set; }
        public Nullable<System.DateTime> ClipTimeStart { get; set; }
        public Nullable<System.DateTime> ClipTimeEnd { get; set; }
        public string ClipVidTimeStart { get; set; }
        public string ClipVidTimeEnd { get; set; }
        public string ClipVidTimeLength { get; set; }
        public string ClipReviewer { get; set; }
        public string CameraOperator { get; set; }
        public string Description { get; set; }
    }
}
